# Streamlit Cloud Secrets Configuration
# This file contains sensitive configuration for the app

[auth]
allowed_emails = ["prjadhav@andrew.cmu.edu"]

# Optional: Secret key for authentication (change this in production)
secret_key = "your-secure-secret-key-change-this" 