# Streamlit Cloud Secrets Configuration
# This file contains sensitive configuration for the app

# Allowed email addresses for authentication
ALLOWED_EMAILS = "prjadhav@andrew.cmu.edu"

# Optional: Secret key for authentication (change this in production)
AUTH_SECRET_KEY = "your-secure-secret-key-change-this" 